# Generated by Django 6.0 on 2025-12-03 21:33

import chatbot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "webhook_key",
                    models.CharField(
                        default=chatbot.models.gen_key, max_length=64, unique=True
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(default=chatbot.models.gen_key, max_length=64),
                ),
                (
                    "vector_namespace",
                    models.CharField(
                        default=chatbot.models.gen_vector_namespace, max_length=200
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, default="You are a helpful assistant."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbots",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
