from django.db import models
from django.contrib.auth import get_user_model
import uuid

User = get_user_model()

def gen_key():
    return uuid.uuid4().hex

class Plan(models.Model):
    name = models.CharField(max_length=100)
    messages_limit = models.IntegerField(default=1000)
    products_limit = models.IntegerField(default=100)

    def __str__(self):
        return self.name

class Tenant(models.Model):
    name = models.CharField(max_length=150)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    plan = models.ForeignKey(Plan, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    # autogenerated workspace key (optional)
    workspace_key = models.CharField(max_length=64, unique=True, default=gen_key)

    def __str__(self):
        return self.name
